# Generated by Django 2.2 on 2021-12-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsAndOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descriptions')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.Product')),
            ],
        ),
    ]
