# Generated by Django 2.2 on 2021-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='shop_list',
            field=models.TextField(default=''),
        ),
    ]
