# Generated by Django 2.2 on 2021-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_active',
            field=models.BooleanField(default=True),
        ),
    ]
