# Generated by Django 2.2 on 2021-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profilemodel_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='num_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
