# Generated by Django 2.2 on 2021-10-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20211028_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
