# Generated by Django 2.2 on 2021-10-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
