# Generated by Django 2.2 on 2021-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20211028_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default='нет', max_length=50, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='нет', max_length=1000, verbose_name='Тэг'),
        ),
    ]
