# Generated by Django 2.2 on 2021-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20211028_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Содержание'),
        ),
    ]
